### ISSUE TITLE
Ajout carte Senegal

### ISSUE THREAD

**Issue by Boss-Demba** [GUISSTANN/features#3]
Je pense qu'il est important d'ajouter une carte du Senegal

**Comment by OusmaneS17** [comment]
[Uploading Donnees_SIG_Sen.zip…]()

**Comment by ndeyadieng1907** [comment]
j'ai trouvé  de trouver une autre carte : https://www.routard.com/guide_carte/code_dest/senegal.htm

**Comment by emilienschultz** [comment]
Merci ! Cette carte est en format raster (image). Pour le projet, nous avons besoin d'une carte vectorielle, qui permet de manipuler les éléments. les formats habituels sont en geojson ou en shapefile.
